# dongyoung
server.port=8031

# dongyoung
server.servlet.session.cookie.name=dongyoung_jsessionid

# dongyoung
spring.datasource.hikari.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.jdbc-url=${DONGYOUNG_DB_URL}


spring.datasource.hikari.username=${DONGYOUNG_DB_USERNAME}
spring.datasource.hikari.password=${DONGYOUNG_DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size = ${DB_MAX}
spring.datasource.hikari.minimum-idle = ${DB_CONNERCTION}
spring.datasource.hikari.maxLifetime = 1800000
spring.datasource.hikari.idle-timeout = 600000
spring.datasource.hikari.leak-detection-threshold=5000

# ------------------------------------------------------------------
# ????? ??????? ?? ?? API
# ------------------------------------------------------------------
# ??API ??? (??: [????]-[??? ????]-[??API ??? ??])
# ? ????? ?? ???? ????? ???? ??? ????,
# ????? ?? ??: smartfactory.log.crtfc-key=${SMARTFACTORY_LOG_KEY}
smartfactory.log.crtfc-key=$5$API$BdEMRE/lvGbEVKfHgLB.VGxKeF8kQn0XZRR6WXDfDV2

smartfactory.log.url=https://log.smart-factory.kr/apisvc/sendLogDataJSON.do

# ???? ??? ?? IP (?? ??)
#  - ?? IP  : 14.36.41.134
#  - ?? ??: 14.36.41.    (???? '.' ?? ??? ??)
#  * 220.77.13.167 ? ?? ?? ??? ???? ???.
#  - 127. / 10. / 192.168. / 172.16. / IPv6 ? ???? ?? ???
smartfactory.log.excluded-ips=14.36.41.134

